baseURL = "https://gbkim01.github.io/blog/"
languageCode = "en-us"
title = "日常茶飯事"
theme = "mero"
disableKinds = ["taxonomyTerm"]
publishDir = "docs"
disqusShortname = "gbkim01"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true 

[params]
  dateFormat = "2006-01-02" 
  author = "日常茶飯事"
  description = "시덥잖은 일들로 시시덕거린다."
  mainImage = "images/main.jpeg"

[params.introduction]
   text1 = "권태가 가시지 않아 뭐라도 할까 싶어 블로그를 만들었다. 마감은 다가오고 발등의 불은 눈썹 까지 옮겨 붙었건만, 모든 책무는 뒤로 미룬 채 불어터진 라면가닥처럼 바닥에 눌러 붙어 있다. 시험을 앞둔 학생이 책상 정리에 열을 올리는 것처럼, 만사 제친 소일거리에 도끼자루가 썩는다."
   text2 = "코딩과는 무관한 문과생이 R과 파이썬을 흘낏한, 사사롭고도 무용한 결과물을 올리는 공간으로 이 블로그를 사용코자 한다. 덤으로 개인사 소소한 사담도 올리고…"

[params.social]
  [[params.social.list]]
#  class = "fab"
#  icon = "fa-linkedin-in"
#  url = "#"

  [[params.social.list]]
#  class = "fab"
#  icon = "fa-github"
#  url = "gbkim01"

  [[params.social.list]]
#  class = "fab"
#  icon = "fa-twitter"
#  url = "#"

  [[params.social.list]]
#  class = "fab"
#  icon = "fa-stack-overflow"
#  url = "#"  

[params.footer]
  message = "&copy; 2019 Gbkim01"
